//
//  Data.h
//
//  Created by Pradyumn Nukala on 8/28/15.
//
#import <Foundation/Foundation.h>
#import "HomeViewController.h"
#import "JASidePanelController.h"
#import "JFMinimalNotification.h"
#import "UIColor+TreeColor.h"
#import "UIViewController+JASidePanel.h"
#import "NSString+EmailAddresses.h"
#import "ForgetPassVC.h"
#import "PNTextField.h"
#import "OrganizationCategory.h"
#import "CategoryOrganizationVC.h"
#import "GivenRequestsViewController.h"
#import "ProvideViewController.h"
#import "OrganizationPostCell.h"
#import "ForeignProfileHeaderView.h"
#import "ForeignProfileVC.h"
#import "MMAlertView.h"
#import "ClubsListVC.h"
#import "LogViewController.h"
#import "INTULocationManager.h"
#import "CreateOrganizationViewController.h"
#import "OrganizationHeaderView.h"
#import "CocoaSecurity.h"
#import "JZMultiChoicesCircleButton.h"
#import "DateTools.h"
#import "STHTTPRequest.h"
#import "BKTPopinControllerViewController.h"
#import "NSArray+StaticArray.h"
#import "AFMSlidingCell.h"
#import "PostViewController.h"
#import "FindOrganizationViewController.h"
#import "OrganizationViewController.h"
#import "SFCollectionViewCell.h"
#import "UIViewController+MaryPopin.h"
#import "IQKeyboardManager.h"
#import "SFManager.h"
#import "SFParser.h"
#import "SFPresenter.h"
#import "SFResource.h"
#import "VolunteerSheetViewController.h"
#import "YCameraViewController.h"
#import "MXParallaxHeader.h"
#import "SFFocusViewLayout.h"
#import "ProfileHeaderView.h"
#import "XLFormRowDescriptor.h"
#import "ProfileTableViewCell.h"
#import "PureLayout.h"
#import "XLForm.h"
#import "XLFormViewController.h"
#import "SettingsViewController.h"
#import "SidebarViewController.h"
#import "TWPhotoPickerController.h"
#import "JBLineChartView.h"
#import "UITableView+ScrollHelpers.h"
#import "CarbonKit.h"
#import "FacebookViewController.h"
#import "CHColorPickerView.h"
#import "JBLineChartFooterView.h"
#import "OrganizationSettingsViewController.h"
#import "JBChartInformationView.h"
#import "JBChartTooltipView.h"
#import "OrganizationDetailViewController.h"
#import "UITextView+Placeholder.h"
#import "ArrayManager.h"
#import "GiveViewController.h"
#import "OrganizationDetailHeaderView.h"
#import "JBConstants.h"
#import "ProfileViewController.h"
#import "UIView+FormScroll.h"
#import "MMAlertView.h"
#import "LGPlusButton.h"
#import "LGPlusButtonDescription.h"
#import "LGPlusButtonsView.h"
#import "LGPlusButtonsViewShared.h"
#import "CocoaWSSE.h"
#import "PureLayout.h"
#import "SearchViewController.h"
#import "UIBarButtonItem+Badge.h"
#import "UIButton+Badge.h"
#import "UsersFindViewController.h"
#import "NotificationViewController.h"
#import "LoginViewController.h"
#import "SettingsViewController.h"
#import "Reachability.h"

@interface Data : NSObject 

+ (int)checkPasswordStrength:(NSString *)password;
+ (NSDate *)currentDate;
+ (NSString *)randomStringWithLength:(int)len;
+ (CGSize)findHeightForText:(NSString *)text havingWidth:(CGFloat)widthValue andFont:(UIFont *)font;

@end
